In [1]:
import pandas as pd
import numpy as np

In [72]:
pd.options.display.float_format = '{:,.2f}'.format

### Problema 1
Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

(a) Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica:__ Utilize as funções `np.random.randint` e `np.reshape`

(b) Retorne a média do vetor

(c) Retorne os menores valores de cada coluna;

(d) Retorne os maiores valores de cada linha.

In [20]:
matriz=np.random.randint(51,size=(5,4))
print(matriz)
matriz.mean()

[[40 43 25 20]
 [23  2 23 45]
 [36 38 38 19]
 [ 9 38 37 48]
 [ 3 38 14 43]]


29.1

In [22]:
matriz.min(axis=0)

array([ 3,  2, 14, 19])

In [23]:
matriz.max(axis=1)

array([43, 45, 38, 48, 43])

### Problema 2

Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:


| Peso (kg) | Altura (cm) | Idade (anos) |
|-----------|-------------|--------------|
|  47 | 161	| 31 |
|  80 | 170	| 21 |
|  60 | 175	| 16 |
|  90 | 162	| 28 |
| 100 | 185	| 23 |
| 147 | 189 | 32 |

Com base no DataFrame criado, realize o que for pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas;

(b) Obtenha a idade média das pessoas;

(c) Obtenha os dados das pessoas que estão abaixo da altura média;

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;

__Obs.:__ A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

(e) Remova a coluna que contém a idade das pessoas;

(f) Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

| IMC             | Classificação |
|-----------------|---------------|
Menor que 18,5    | Subpeso |
Entre 18,5 e 24,9 | Normal |
Entre 25,0 e 29,9 | Sobrepeso |
Entre 30,0 e 39,9 | Obesidade Grau I |
Maior que 40,0    | Obesidade Grau II |

(g) Salve esses dados do DataFrame em um arquivo csv.

In [98]:
obj = {'Peso': [47,80,60,90,100,147], 'Altura': [161, 170,175,162,185,189],'Idade':[31,21,16,28,23,32]}

In [99]:
df=pd.DataFrame(data=obj)
df

Peso  Altura  Idade
0    47     161     31
1    80     170     21
2    60     175     16
3    90     162     28
4   100     185     23
5   147     189     32

In [100]:
obj['Altura']

[161, 170, 175, 162, 185, 189]

In [101]:
media_idade=np.mean(obj['Idade'])

In [102]:
media_altura=np.mean(obj['Altura'])

In [103]:
df[df['Altura']<media_altura]

Peso  Altura  Idade
0    47     161     31
1    80     170     21
3    90     162     28

In [104]:
df['IMC']=df['Peso']/(df['Altura']/100)**2
df

Peso  Altura  Idade        IMC
0    47     161     31  18.132017
1    80     170     21  27.681661
2    60     175     16  19.591837
3    90     162     28  34.293553
4   100     185     23  29.218408
5   147     189     32  41.152263

In [105]:
df=df.drop('Idade', axis = 1)

In [106]:
df

Peso  Altura        IMC
0    47     161  18.132017
1    80     170  27.681661
2    60     175  19.591837
3    90     162  34.293553
4   100     185  29.218408
5   147     189  41.152263

In [114]:
conditionlist = [
    (df['IMC'] < 18.5) ,
    (df['IMC'] > 18.5) & (df['IMC'] <24.9),
    (df['IMC'] >=25.0) & (df['IMC']<29.9),
    (df['IMC']>=30.0) & (df['IMC']<39.9),
    (df['IMC'] >= 40.0)]
choicelist = ['Subpeso', 'Normal', 'Sobrepeso', 'Obesidade I','Obesidade II']

df['Classificacoa'] = np.select(conditionlist, choicelist, default='Not Specified')

In [115]:
df

Peso  Altura        IMC Classificacoa
0    47     161  18.132017       Subpeso
1    80     170  27.681661     Sobrepeso
2    60     175  19.591837        Normal
3    90     162  34.293553   Obesidade I
4   100     185  29.218408     Sobrepeso
5   147     189  41.152263  Obesidade II

### Problema 3

O arquivo avocado.xlsx consiste em um dataset que contém dados sobre vendas de abacates  em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

| Coluna | Descrição |
|--------|-----------|
| Date | data da observação |
| AveragePrice | preço médio de um único abacate |
| year | ano |
| region | cidade ou região da observação |
| Total Volume | volume total de abacates vendidos |

Além das informações acima, contidas no arquivo avocado.xlsx, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo avocado.csv, na mesma ordem, e salvou-as no arquivo avocado_type.xlsx. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame.

Com o DataFrame criado, obtenha o que é solicitado nos itens elencados abaixo:




In [122]:
!pip install openpyxl

You should consider upgrading via the 'C:\Users\Mariana\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [182]:
df_avocado = pd.read_csv("./data/avocado.csv",delimiter=';')
df_avocado_type = pd.read_excel("./data/avocado_type.xlsx")
df_avocado['type'] = df_avocado_type

In [183]:
df_avocado

Date  AveragePrice  Total Volume  year            region  \
0      2015-12-27          1.33      64236.62  2015            Albany   
1      2015-12-20          1.35      54876.98  2015            Albany   
2      2015-12-13          0.93     118220.22  2015            Albany   
3      2015-12-06          1.08      78992.15  2015            Albany   
4      2015-11-29          1.28      51039.60  2015            Albany   
...           ...           ...           ...   ...               ...   
18244  2018-02-04          1.63      17074.83  2018  WestTexNewMexico   
18245  2018-01-28          1.71      13888.04  2018  WestTexNewMexico   
18246  2018-01-21          1.87      13766.76  2018  WestTexNewMexico   
18247  2018-01-14          1.93      16205.22  2018  WestTexNewMexico   
18248  2018-01-07          1.62      17489.58  2018  WestTexNewMexico   

               type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(a) A quantidade de abacates do tipo convecional e do tipo orgânico.

In [184]:
df_avocado.groupby(by='type').size()

type
convencional    9114
orgânico        9135
dtype: int64


(b) A quantidade de registros (linhas) de abacates vendidos para cada região ordenada da maior venda para a menor.

In [185]:
df_avocado.groupby(by='region').size()

region
Albany                 338
Atlanta                338
BaltimoreWashington    338
Boise                  338
Boston                 338
BuffaloRochester       338
California             338
Charlotte              338
Chicago                338
CincinnatiDayton       338
Columbus               338
DallasFtWorth          338
Denver                 338
Detroit                338
GrandRapids            338
GreatLakes             338
HarrisburgScranton     338
HartfordSpringfield    338
Houston                338
Indianapolis           338
Jacksonville           338
LasVegas               338
LosAngeles             338
Louisville             338
MiamiFtLauderdale      338
Midsouth               338
Nashville              338
NewOrleansMobile       338
NewYork                338
Northeast              338
NorthernNewEngland     338
Orlando                338
Philadelphia           338
PhoenixTucson          338
Pittsburgh             338
Plains                 338
Portland             

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula, trocando espaço por _ e adicionando _ como separação de texto.

In [193]:
df_avocado=df_avocado.rename(columns={'AveragePrice':'Average_Price', 'Total Volume':'Total_Volume','year':'Year','region':'Region','type':'Type'})

(d) Essa dado possui duplicados? Se sim, remova-os do dataset.

In [194]:
#Nao possui duplicadas
df_avocado=df_avocado.drop_duplicates()


In [195]:
df_avocado

Date  Average_Price  Total_Volume  Year            Region  \
0      2015-12-27           1.33      64236.62  2015            Albany   
1      2015-12-20           1.35      54876.98  2015            Albany   
2      2015-12-13           0.93     118220.22  2015            Albany   
3      2015-12-06           1.08      78992.15  2015            Albany   
4      2015-11-29           1.28      51039.60  2015            Albany   
...           ...            ...           ...   ...               ...   
18244  2018-02-04           1.63      17074.83  2018  WestTexNewMexico   
18245  2018-01-28           1.71      13888.04  2018  WestTexNewMexico   
18246  2018-01-21           1.87      13766.76  2018  WestTexNewMexico   
18247  2018-01-14           1.93      16205.22  2018  WestTexNewMexico   
18248  2018-01-07           1.62      17489.58  2018  WestTexNewMexico   

               Type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(e) Retire dos dados a região 'TotalUS'

In [196]:
df_avocado = df_avocado[df_avocado['Region'] != 'TotalUS']

(g) Apresente as regiões que mais venderam abacate em todo o período em ordem decrescente.

In [202]:
df_avocado.groupby(['Region']).agg({'Total_Volume':np.sum}).sort_values(by="Total_Volume",ascending=False)

Total_Volume
Region                           
West                 1.086779e+09
California           1.028982e+09
SouthCentral         1.011280e+09
Northeast            7.132809e+08
Southeast            6.152384e+08
GreatLakes           5.896425e+08
Midsouth             5.083494e+08
LosAngeles           5.078965e+08
Plains               3.111885e+08
NewYork              2.407341e+08
DallasFtWorth        2.084193e+08
Houston              2.031679e+08
PhoenixTucson        1.956433e+08
WestTexNewMexico     1.445218e+08
Denver               1.389025e+08
SanFrancisco         1.358302e+08
BaltimoreWashington  1.347139e+08
Chicago              1.337023e+08
Portland             1.105522e+08
Seattle              1.092142e+08
MiamiFtLauderdale    9.767322e+07
Boston               9.727398e+07
SanDiego             8.979192e+07
Atlanta              8.860512e+07
Sacramento           7.516375e+07
Philadelphia         7.183880e+07
NorthernNewEngland   7.153289e+07
Tampa                6.600454e+07
Detroit              6.342242e+07
SouthCarolina        6.075377e+07
Orlando              5.866070e+07
LasVegas             5.437691e+07
HartfordSpringfield  5.067054e+07
RaleighGreensboro    4.820273e+07
NewOrleansMobile     4.569514e+07
CincinnatiDayton     4.452201e+07
RichmondNorfolk      4.223085e+07
HarrisburgScranton   4.180886e+07
Nashville            3.561209e+07
Charlotte            3.555554e+07
StLouis              3.207283e+07
Indianapolis         3.026339e+07
GrandRapids          3.021174e+07
Columbus             2.999336e+07
Jacksonville         2.879000e+07
Roanoke              2.504201e+07
BuffaloRochester     2.296247e+07
Pittsburgh           1.880635e+07
Louisville           1.609700e+07
Albany               1.606780e+07
Spokane              1.556528e+07
Boise                1.441319e+07
Syracuse             1.094267e+07

(h) Calcule o volume total de abacates vendidos para cada tipo e ano.

In [201]:
df_avocado.groupby(['Type','Year']).agg({'Total_Volume':np.sum})

Total_Volume
Type         Year              
convencional 2015  1.405836e+09
             2016  1.538914e+09
             2017  1.505464e+09
             2018  4.337104e+08
orgânico     2015  1.322378e+09
             2016  1.462817e+09
             2017  1.564148e+09
             2018  4.253956e+08

(f) existe alguma região que foi a maior responsável pela queda na produção de 2018?

In [204]:
df_avocado[df_avocado['Year']==2018].groupby(['Region']).agg({'Total_Volume':np.sum}).sort_values(by="Total_Volume",ascending=True)

Total_Volume
Region                           
Syracuse               1046987.66
Boise                  1214759.57
Spokane                1225893.47
Louisville             1471561.01
Albany                 1541986.17
Pittsburgh             1901519.72
BuffaloRochester       2123818.04
Roanoke                2490769.90
StLouis                2537659.99
GrandRapids            2569463.33
Jacksonville           2708404.34
Columbus               2843900.00
Indianapolis           2908674.80
Nashville              3512353.35
Charlotte              3585889.60
CincinnatiDayton       3598287.29
HarrisburgScranton     3901811.84
RichmondNorfolk        3994823.06
NewOrleansMobile       4063960.67
HartfordSpringfield    4487740.65
LasVegas               4493631.50
RaleighGreensboro      4788895.28
SouthCarolina          5836081.34
Orlando                5914938.97
Detroit                6022957.35
Philadelphia           6567236.92
NorthernNewEngland     6636168.55
Tampa                  6642055.00
SanDiego               6673850.49
Sacramento             6867749.76
Seattle                7941094.35
Atlanta                8231422.45
Portland               8397790.46
Boston                 8637005.96
MiamiFtLauderdale      9741420.63
Chicago               11614231.61
WestTexNewMexico      11800820.78
Denver                11845353.40
BaltimoreWashington   12158903.00
SanFrancisco          12983259.27
PhoenixTucson         18012805.53
DallasFtWorth         18171745.33
Houston               19982517.11
NewYork               23729255.17
Plains                28028072.96
LosAngeles            38052377.59
Midsouth              48313392.04
GreatLakes            53160677.97
Southeast             60284470.54
Northeast             66323536.84
California            83741308.94
SouthCentral          91303709.48
West                  92477085.01

(g) Qual cidade menos faturou com a venda de abacates?

In [209]:
df_avocado['Faturamento']=df_avocado['Total_Volume']*df_avocado['Average_Price']

C:\Users\Mariana\AppData\Local\Temp/ipykernel_10996/4080306345.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_avocado['Faturamento']=df_avocado['Total_Volume']*df_avocado['Average_Price']


In [216]:
df_avocado.groupby(['Region']).agg({'Faturamento':np.sum}).sort_values(by='Faturamento', ascending=True)

Faturamento
Region                           
Syracuse             1.520519e+07
Boise                1.534667e+07
Spokane              1.715649e+07
Louisville           1.749555e+07
Albany               2.176672e+07
Pittsburgh           2.319481e+07
Roanoke              2.740928e+07
BuffaloRochester     3.154509e+07
Columbus             3.156295e+07
Jacksonville         3.348396e+07
Indianapolis         3.402474e+07
Nashville            3.572664e+07
StLouis              3.743946e+07
GrandRapids          3.785124e+07
CincinnatiDayton     4.498958e+07
Charlotte            4.574304e+07
RichmondNorfolk      4.734482e+07
NewOrleansMobile     4.867626e+07
HarrisburgScranton   5.295472e+07
LasVegas             5.480905e+07
RaleighGreensboro    5.983780e+07
Detroit              6.912624e+07
SouthCarolina        6.952808e+07
Orlando              6.961121e+07
HartfordSpringfield  7.118645e+07
Tampa                7.695906e+07
NorthernNewEngland   8.962525e+07
SanDiego             9.352710e+07
Atlanta              9.379337e+07
Sacramento           9.480870e+07
Philadelphia         9.981583e+07
Portland             1.128646e+08
MiamiFtLauderdale    1.185815e+08
WestTexNewMexico     1.215654e+08
Seattle              1.251791e+08
Boston               1.265429e+08
PhoenixTucson        1.384515e+08
Denver               1.459828e+08
Houston              1.655713e+08
DallasFtWorth        1.756093e+08
Chicago              1.791106e+08
BaltimoreWashington  1.799084e+08
SanFrancisco         1.858341e+08
NewYork              3.351955e+08
Plains               3.600366e+08
LosAngeles           4.842276e+08
Midsouth             6.157238e+08
GreatLakes           6.886618e+08
Southeast            7.036306e+08
SouthCentral         8.740593e+08
Northeast            9.600079e+08
West                 1.066834e+09
California           1.121414e+09

### Problema 4

Com base no dataset 'Video_Games_Sales.csv' responda:



(a) Quantos jogos existem em cada genero?


In [217]:
df_games = pd.read_csv("./data/Video_Games_Sales.csv",delimiter=';')

In [218]:
df_games

Name Platform  Year_of_Release         Genre  \
0                         Wii Sports      Wii           2006.0        Sports   
1                  Super Mario Bros.      NES           1985.0      Platform   
2                     Mario Kart Wii      Wii           2008.0        Racing   
3                  Wii Sports Resort      Wii           2009.0        Sports   
4           Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing   
...                              ...      ...              ...           ...   
16714  Samurai Warriors: Sanada Maru      PS3           2016.0        Action   
16715               LMA Manager 2007     X360           2006.0        Sports   
16716        Haitaka no Psychedelica      PSV           2016.0     Adventure   
16717               Spirits & Spells      GBA           2003.0      Platform   
16718            Winning Post 8 2016      PSV           2016.0    Simulation   

          Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0          Nintendo     41.36     28.96      3.77         8.45         82.53   
1          Nintendo     29.08      3.58      6.81         0.77         40.24   
2          Nintendo     15.68     12.76      3.79         3.29         35.52   
3          Nintendo     15.61     10.93      3.28         2.95         32.77   
4          Nintendo     11.27      8.89     10.22         1.00         31.37   
...             ...       ...       ...       ...          ...           ...   
16714    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   
16715   Codemasters      0.00      0.01      0.00         0.00          0.01   
16716  Idea Factory      0.00      0.00      0.01         0.00          0.01   
16717       Wanadoo      0.01      0.00      0.00         0.00          0.01   
16718    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   

       Critic_Score  Critic_Count  User_Score  User_Count Developer Rating  
0              76.0          51.0         8.0       322.0  Nintendo      E  
1               NaN           NaN         NaN         NaN       NaN    NaN  
2              82.0          73.0         8.3       709.0  Nintendo      E  
3              80.0          73.0         8.0       192.0  Nintendo      E  
4               NaN           NaN         NaN         NaN       NaN    NaN  
...             ...           ...         ...         ...       ...    ...  
16714           NaN           NaN         NaN         NaN       NaN    NaN  
16715           NaN           NaN         NaN         NaN       NaN    NaN  
16716           NaN           NaN         NaN         NaN       NaN    NaN  
16717           NaN           NaN         NaN         NaN       NaN    NaN  
16718           NaN           NaN         NaN         NaN       NaN    NaN  

[16719 rows x 16 columns]

(b) Temos duplicados nesses dados? E nulos?

In [221]:
df_games=df_games.drop_duplicates()


In [224]:
df_games.isnull().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         9129
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [222]:
df_games

Name Platform  Year_of_Release         Genre  \
0                         Wii Sports      Wii           2006.0        Sports   
1                  Super Mario Bros.      NES           1985.0      Platform   
2                     Mario Kart Wii      Wii           2008.0        Racing   
3                  Wii Sports Resort      Wii           2009.0        Sports   
4           Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing   
...                              ...      ...              ...           ...   
16714  Samurai Warriors: Sanada Maru      PS3           2016.0        Action   
16715               LMA Manager 2007     X360           2006.0        Sports   
16716        Haitaka no Psychedelica      PSV           2016.0     Adventure   
16717               Spirits & Spells      GBA           2003.0      Platform   
16718            Winning Post 8 2016      PSV           2016.0    Simulation   

          Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0          Nintendo     41.36     28.96      3.77         8.45         82.53   
1          Nintendo     29.08      3.58      6.81         0.77         40.24   
2          Nintendo     15.68     12.76      3.79         3.29         35.52   
3          Nintendo     15.61     10.93      3.28         2.95         32.77   
4          Nintendo     11.27      8.89     10.22         1.00         31.37   
...             ...       ...       ...       ...          ...           ...   
16714    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   
16715   Codemasters      0.00      0.01      0.00         0.00          0.01   
16716  Idea Factory      0.00      0.00      0.01         0.00          0.01   
16717       Wanadoo      0.01      0.00      0.00         0.00          0.01   
16718    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   

       Critic_Score  Critic_Count  User_Score  User_Count Developer Rating  
0              76.0          51.0         8.0       322.0  Nintendo      E  
1               NaN           NaN         NaN         NaN       NaN    NaN  
2              82.0          73.0         8.3       709.0  Nintendo      E  
3              80.0          73.0         8.0       192.0  Nintendo      E  
4               NaN           NaN         NaN         NaN       NaN    NaN  
...             ...           ...         ...         ...       ...    ...  
16714           NaN           NaN         NaN         NaN       NaN    NaN  
16715           NaN           NaN         NaN         NaN       NaN    NaN  
16716           NaN           NaN         NaN         NaN       NaN    NaN  
16717           NaN           NaN         NaN         NaN       NaN    NaN  
16718           NaN           NaN         NaN         NaN       NaN    NaN  

[16719 rows x 16 columns]

(b) Quantos jogos de cada publisher receberam nota acima de 9 na avaliação dos usuarios?

In [235]:
df_games[df_games['User_Score']>9.0].groupby('Publisher').agg({'User_Score':np.size})

User_Score
Publisher                                     
505 Games                                    1
Acclaim Entertainment                        2
Activision                                  16
Activision Value                             1
Atari                                        7
Atlus                                        2
Bethesda Softworks                           1
Capcom                                       9
Codemasters                                  1
Destination Software, Inc                    1
Disney Interactive Studios                   1
Eidos Interactive                            5
Electronic Arts                             19
GT Interactive                               1
Ignition Entertainment                       1
Infogrames                                   1
Interplay                                    1
Jaleco                                       1
Kadokawa Shoten                              1
Kemco                                        1
Konami Digital Entertainment                10
LucasArts                                    1
Marvelous Interactive                        2
Metro 3D                                     1
Microsoft Game Studios                       2
Midway Games                                 5
Namco Bandai Games                           6
Nintendo                                    20
PQube                                        2
Sega                                         7
Sony Computer Entertainment                  7
Sony Computer Entertainment Europe           3
Square                                       1
Square Enix                                  1
Sting                                        1
Sunflowers                                   1
THQ                                         10
Take-Two Interactive                         4
Tecmo Koei                                   9
Telegames                                    1
Ubisoft                                      5
ValuSoft                                     1
Virgin Interactive                           1
Vivendi Games                                8
Zoo Digital Publishing                       2


(c) Faça uma tabela que mostre o total vendido por ano por pais/globalmente de cada publisher? Você consegue observar algum padrão? Com se comportaram as vendas na América do Norte (NA) ao longo do tempo? O mesmo foi visto nos demais lugares? 


In [250]:
pd.set_option('display.max_rows', None)

In [252]:
df_games.groupby(['Publisher','Year_of_Release']).agg({'Other_Sales':np.sum,'NA_Sales':np.sum,'EU_Sales':np.sum,'JP_Sales':np.sum})

Other_Sales  NA_Sales  \
Publisher                              Year_of_Release                          
10TACLE Studios                        2006.0                  0.00      0.01   
                                       2007.0                  0.00      0.06   
1C Company                             2009.0                  0.00      0.00   
                                       2011.0                  0.01      0.01   
20th Century Fox Video Games           1981.0                  0.01      1.27   
                                       1982.0                  0.00      0.55   
2D Boy                                 2008.0                  0.01      0.00   
3DO                                    1998.0                  0.00      0.30   
                                       1999.0                  0.17      3.01   
                                       2000.0                  0.18      1.86   
                                       2001.0                  0.15      0.76   
                                       2002.0                  0.08      0.30   
                                       2003.0                  0.05      0.25   
49Games                                2009.0                  0.00      0.00   
505 Games                              2002.0                  0.01      0.02   
                                       2003.0                  0.01      0.05   
                                       2004.0                  0.09      0.49   
                                       2005.0                  0.09      0.89   
                                       2006.0                  0.68      4.10   
                                       2007.0                  0.97      6.04   
                                       2008.0                  0.20      2.07   
                                       2009.0                  0.70      4.67   
                                       2010.0                  1.31      8.41   
                                       2011.0                  0.34      1.95   
                                       2012.0                  0.26      0.89   
                                       2013.0                  0.25      1.01   
                                       2014.0                  0.23      0.70   
                                       2015.0                  0.09      0.25   
                                       2016.0                  0.08      0.09   
5pb                                    2008.0                  0.00      0.00   
                                       2009.0                  0.00      0.00   
                                       2010.0                  0.00      0.00   
                                       2011.0                  0.00      0.02   
                                       2012.0                  0.00      0.00   
                                       2013.0                  0.00      0.00   
                                       2014.0                  0.00      0.00   
                                       2015.0                  0.00      0.00   
                                       2016.0                  0.00      0.00   
7G//AMES                               2011.0                  0.00      0.00   
989 Sports                             1999.0                  0.02      0.21   
989 Studios                            1997.0                  0.04      0.29   
                                       1998.0                  0.32      5.66   
                                       1999.0                  0.31      3.28   
AQ Interactive                         2007.0                  0.02      0.06   
                                       2008.0                  0.02      0.19   
                                       2009.0                  0.01      0.07   
ASC Games                              1996.0                  0.09      0.73   
                                       1998.0                  0.04      0.36   
      


(d) Qual foi jogo mais vendido na união européia? De que ano ele é e qual a editora?


In [253]:
df_games.groupby(['Name','Publisher','Year_of_Release']).agg({'EU_Sales':np.sum}).sort_values(by='EU_Sales', ascending=False).head(1)

EU_Sales
Name       Publisher Year_of_Release          
Wii Sports Nintendo  2006.0              28.96


(e) Quantos % os generos ['Racing', 'Sports', 'Shooter'] representam na base de dados? 

In [259]:
df_games['Global_Sales'][(df_games['Genre'] == 'Racing')].sum() / df_games['Global_Sales'].sum()

0.08171249845857202

In [260]:
df_games['Global_Sales'][(df_games['Genre'] == 'Sports')].sum() / df_games['Global_Sales'].sum()

0.14932233220855798

In [261]:
df_games['Global_Sales'] [(df_games['Genre'] == 'Shooter')].sum() / df_games['Global_Sales'].sum()

0.11803863098774701

(f) Qual plataforma vendeu menos globalmente? obs: imprimir somente o nome

In [282]:
df_games.groupby(['Platform']).agg({'Global_Sales':np.sum}).sort_values(by='Global_Sales', ascending=True).head(1).index[0]

'PCFX'

### Problema 5
A pasta 'data/datasus' contém informações sobre casos de dengue e tabelas auxiliares. <br>

| Tabela | Conteúdo |
|--------|----------|
| Dengue | Quantidade de casos por município |
| Agua | Quantidade de residências em cada município por tipo o abastecimento de água |
| InstalacoesSanitarias | Quantidade de residências em cada município por tipo de rede de esgoto |
| Pib | PIB per capita de cada município |
| Municipios | Relaciona o id_municipio com seu nome e estado |
| Populacao | Quantidade de pessoas morando em áreas urbanas, rurais e população total por município |
| Sexo | Quantidade de pessoas por sexo em cada município |

(a) Calcular o número de casos de dengue por cada estado apresentando os dados em ordem decrescente.


(b) Utilizando o dataset InstalacoesSanitarias.csv, determine o número de pessoas que não possuem meio sanitário algum de descarte de dejetos por estado.

(c) Crie uma coluna com a posição de ranking considerando o PIB. Os maiores PIB devem ter os menores valores de ranking.

(d) Qual o PIB dos 5 municípios com mais casos de dengue e sua posição no ranking?